//
// This is a generated file, do not edit!
// Generated by R.swift, see https://github.com/mac-cain13/R.swift
//

import Foundation
import Rswift
import UIKit

/// This `R` struct is generated and contains references to static resources.
struct R: Rswift.Validatable {
  fileprivate static let applicationLocale = hostingBundle.preferredLocalizations.first.flatMap { Locale(identifier: $0) } ?? Locale.current
  fileprivate static let hostingBundle = Bundle(for: R.Class.self)

  /// Find first language and bundle for which the table exists
  fileprivate static func localeBundle(tableName: String, preferredLanguages: [String]) -> (Foundation.Locale, Foundation.Bundle)? {
    // Filter preferredLanguages to localizations, use first locale
    var languages = preferredLanguages
      .map { Locale(identifier: $0) }
      .prefix(1)
      .flatMap { locale -> [String] in
        if hostingBundle.localizations.contains(locale.identifier) {
          if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
            return [locale.identifier, language]
          } else {
            return [locale.identifier]
          }
        } else if let language = locale.languageCode, hostingBundle.localizations.contains(language) {
          return [language]
        } else {
          return []
        }
      }

    // If there's no languages, use development language as backstop
    if languages.isEmpty {
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages = [developmentLocalization]
      }
    } else {
      // Insert Base as second item (between locale identifier and languageCode)
      languages.insert("Base", at: 1)

      // Add development language as backstop
      if let developmentLocalization = hostingBundle.developmentLocalization {
        languages.append(developmentLocalization)
      }
    }

    // Find first language for which table exists
    // Note: key might not exist in chosen language (in that case, key will be shown)
    for language in languages {
      if let lproj = hostingBundle.url(forResource: language, withExtension: "lproj"),
         let lbundle = Bundle(url: lproj)
      {
        let strings = lbundle.url(forResource: tableName, withExtension: "strings")
        let stringsdict = lbundle.url(forResource: tableName, withExtension: "stringsdict")

        if strings != nil || stringsdict != nil {
          return (Locale(identifier: language), lbundle)
        }
      }
    }

    // If table is available in main bundle, don't look for localized resources
    let strings = hostingBundle.url(forResource: tableName, withExtension: "strings", subdirectory: nil, localization: nil)
    let stringsdict = hostingBundle.url(forResource: tableName, withExtension: "stringsdict", subdirectory: nil, localization: nil)

    if strings != nil || stringsdict != nil {
      return (applicationLocale, hostingBundle)
    }

    // If table is not found for requested languages, key will be shown
    return nil
  }

  /// Load string from Info.plist file
  fileprivate static func infoPlistString(path: [String], key: String) -> String? {
    var dict = hostingBundle.infoDictionary
    for step in path {
      guard let obj = dict?[step] as? [String: Any] else { return nil }
      dict = obj
    }
    return dict?[key] as? String
  }

  static func validate() throws {
    try intern.validate()
  }

  #if os(iOS) || os(tvOS)
  /// This `R.storyboard` struct is generated, and contains static references to 1 storyboards.
  struct storyboard {
    /// Storyboard `LaunchScreen`.
    static let launchScreen = _R.storyboard.launchScreen()

    #if os(iOS) || os(tvOS)
    /// `UIStoryboard(name: "LaunchScreen", bundle: ...)`
    static func launchScreen(_: Void = ()) -> UIKit.UIStoryboard {
      return UIKit.UIStoryboard(resource: R.storyboard.launchScreen)
    }
    #endif

    fileprivate init() {}
  }
  #endif

  /// This `R.color` struct is generated, and contains static references to 4 colors.
  struct color {
    /// Color `blueColor`.
    static let blueColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "blueColor")
    /// Color `chanelColor`.
    static let chanelColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "chanelColor")
    /// Color `programColor`.
    static let programColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "programColor")
    /// Color `separatorColor`.
    static let separatorColor = Rswift.ColorResource(bundle: R.hostingBundle, name: "separatorColor")

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "blueColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func blueColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.blueColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "chanelColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func chanelColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.chanelColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "programColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func programColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.programColor, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIColor(named: "separatorColor", bundle: ..., traitCollection: ...)`
    @available(tvOS 11.0, *)
    @available(iOS 11.0, *)
    static func separatorColor(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIColor? {
      return UIKit.UIColor(resource: R.color.separatorColor, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.image` struct is generated, and contains static references to 3 images.
  struct image {
    /// Image `icon_arrow_left`.
    static let icon_arrow_left = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_arrow_left")
    /// Image `icon_arrow_right`.
    static let icon_arrow_right = Rswift.ImageResource(bundle: R.hostingBundle, name: "icon_arrow_right")
    /// Image `navBar_back`.
    static let navBar_back = Rswift.ImageResource(bundle: R.hostingBundle, name: "navBar_back")

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icon_arrow_left", bundle: ..., traitCollection: ...)`
    static func icon_arrow_left(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_arrow_left, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "icon_arrow_right", bundle: ..., traitCollection: ...)`
    static func icon_arrow_right(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.icon_arrow_right, compatibleWith: traitCollection)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UIImage(named: "navBar_back", bundle: ..., traitCollection: ...)`
    static func navBar_back(compatibleWith traitCollection: UIKit.UITraitCollection? = nil) -> UIKit.UIImage? {
      return UIKit.UIImage(resource: R.image.navBar_back, compatibleWith: traitCollection)
    }
    #endif

    fileprivate init() {}
  }

  /// This `R.nib` struct is generated, and contains static references to 5 nibs.
  struct nib {
    /// Nib `SMChannelCell`.
    static let smChannelCell = _R.nib._SMChannelCell()
    /// Nib `SMChannelsViewController`.
    static let smChannelsViewController = _R.nib._SMChannelsViewController()
    /// Nib `SMEmptyCell`.
    static let smEmptyCell = _R.nib._SMEmptyCell()
    /// Nib `SMProgramCell`.
    static let smProgramCell = _R.nib._SMProgramCell()
    /// Nib `SMTimeCell`.
    static let smTimeCell = _R.nib._SMTimeCell()

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SMChannelCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.smChannelCell) instead")
    static func smChannelCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.smChannelCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SMChannelsViewController", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.smChannelsViewController) instead")
    static func smChannelsViewController(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.smChannelsViewController)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SMEmptyCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.smEmptyCell) instead")
    static func smEmptyCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.smEmptyCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SMProgramCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.smProgramCell) instead")
    static func smProgramCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.smProgramCell)
    }
    #endif

    #if os(iOS) || os(tvOS)
    /// `UINib(name: "SMTimeCell", in: bundle)`
    @available(*, deprecated, message: "Use UINib(resource: R.nib.smTimeCell) instead")
    static func smTimeCell(_: Void = ()) -> UIKit.UINib {
      return UIKit.UINib(resource: R.nib.smTimeCell)
    }
    #endif

    static func smChannelCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMChannelCell? {
      return R.nib.smChannelCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMChannelCell
    }

    static func smChannelsViewController(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
      return R.nib.smChannelsViewController.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
    }

    static func smEmptyCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMEmptyCell? {
      return R.nib.smEmptyCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMEmptyCell
    }

    static func smProgramCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMProgramCell? {
      return R.nib.smProgramCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMProgramCell
    }

    static func smTimeCell(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMTimeCell? {
      return R.nib.smTimeCell.instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMTimeCell
    }

    fileprivate init() {}
  }

  /// This `R.string` struct is generated, and contains static references to 1 localization tables.
  struct string {
    /// This `R.string.localizable` struct is generated, and contains static references to 1 localization keys.
    struct localizable {
      /// en translation: OK
      ///
      /// Locales: en
      static let ok = Rswift.StringResource(key: "ok", tableName: "Localizable", bundle: R.hostingBundle, locales: ["en"], comment: nil)

      /// en translation: OK
      ///
      /// Locales: en
      static func ok(preferredLanguages: [String]? = nil) -> String {
        guard let preferredLanguages = preferredLanguages else {
          return NSLocalizedString("ok", bundle: hostingBundle, comment: "")
        }

        guard let (_, bundle) = localeBundle(tableName: "Localizable", preferredLanguages: preferredLanguages) else {
          return "ok"
        }

        return NSLocalizedString("ok", bundle: bundle, comment: "")
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }

  fileprivate struct intern: Rswift.Validatable {
    fileprivate static func validate() throws {
      try _R.validate()
    }

    fileprivate init() {}
  }

  fileprivate class Class {}

  fileprivate init() {}
}

struct _R: Rswift.Validatable {
  static func validate() throws {
    #if os(iOS) || os(tvOS)
    try storyboard.validate()
    #endif
  }

  #if os(iOS) || os(tvOS)
  struct nib {
    struct _SMChannelCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SMChannelCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMChannelCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMChannelCell
      }

      fileprivate init() {}
    }

    struct _SMChannelsViewController: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SMChannelsViewController"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> UIKit.UIView? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? UIKit.UIView
      }

      fileprivate init() {}
    }

    struct _SMEmptyCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SMEmptyCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMEmptyCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMEmptyCell
      }

      fileprivate init() {}
    }

    struct _SMProgramCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SMProgramCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMProgramCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMProgramCell
      }

      fileprivate init() {}
    }

    struct _SMTimeCell: Rswift.NibResourceType {
      let bundle = R.hostingBundle
      let name = "SMTimeCell"

      func firstView(owner ownerOrNil: AnyObject?, options optionsOrNil: [UINib.OptionsKey : Any]? = nil) -> SMTimeCell? {
        return instantiate(withOwner: ownerOrNil, options: optionsOrNil)[0] as? SMTimeCell
      }

      fileprivate init() {}
    }

    fileprivate init() {}
  }
  #endif

  #if os(iOS) || os(tvOS)
  struct storyboard: Rswift.Validatable {
    static func validate() throws {
      #if os(iOS) || os(tvOS)
      try launchScreen.validate()
      #endif
    }

    #if os(iOS) || os(tvOS)
    struct launchScreen: Rswift.StoryboardResourceWithInitialControllerType, Rswift.Validatable {
      typealias InitialController = UIKit.UIViewController

      let bundle = R.hostingBundle
      let name = "LaunchScreen"

      static func validate() throws {
        if #available(iOS 11.0, tvOS 11.0, *) {
        }
      }

      fileprivate init() {}
    }
    #endif

    fileprivate init() {}
  }
  #endif

  fileprivate init() {}
}
